In [34]:
import numpy as np
import pandas as pd

In [35]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arr=arr.reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
df=pd.DataFrame(arr,index=['rows1','rows2','rows3','rows4','rows5'],columns=['columns1','columns2','columns3','columns4'])
df

columns1  columns2  columns3  columns4
rows1         0         1         2         3
rows2         4         5         6         7
rows3         8         9        10        11
rows4        12        13        14        15
rows5        16        17        18        19

In [38]:
"""for converting to csf file"""
df.to_csv('df2.csv',index=False)


In [60]:
"""for indexing dataframe """
# loc function --> chooses rows

df.loc['rows1']
type(df.loc['rows1'])

pandas.core.series.Series

In [66]:
# iloc --> chooses multiple rows and columns
df.iloc[3:5,1:4]

columns2  columns3  columns4
rows4        13        14        15
rows5        17        18        19

In [68]:
# for converting dataframes into arrays 

df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [70]:
df.iloc[3:5,1:4].values

array([[13, 14, 15],
       [17, 18, 19]])

In [73]:
# how many times value of column1 is repeating..
df['columns1'].value_counts()

columns1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [80]:
# very important function it is checking if there is any null values in the program or not
df.isnull().sum()

columns1    0
columns2    0
columns3    0
columns4    0
dtype: int64

In [90]:
# checking unique values column vise
df['columns2'].unique()

array([ 1,  5,  9, 13, 17])