In [67]:
import numpy as np
import pandas as pd

In [35]:
arr=np.arange(0,20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
arr=arr.reshape(5,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [37]:
df=pd.DataFrame(arr,index=['rows1','rows2','rows3','rows4','rows5'],columns=['columns1','columns2','columns3','columns4'])
df

columns1  columns2  columns3  columns4
rows1         0         1         2         3
rows2         4         5         6         7
rows3         8         9        10        11
rows4        12        13        14        15
rows5        16        17        18        19

In [38]:
"""for converting to csf file"""
df.to_csv('df2.csv',index=False)


In [60]:
"""for indexing dataframe """
# loc function --> chooses rows

df.loc['rows1']
type(df.loc['rows1'])

pandas.core.series.Series

In [66]:
# iloc --> chooses multiple rows and columns
df.iloc[3:5,1:4]

columns2  columns3  columns4
rows4        13        14        15
rows5        17        18        19

In [68]:
# for converting dataframes into arrays 

df.values

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [70]:
df.iloc[3:5,1:4].values

array([[13, 14, 15],
       [17, 18, 19]])

In [73]:
# how many times value of column1 is repeating..
df['columns1'].value_counts()

columns1
0     1
4     1
8     1
12    1
16    1
Name: count, dtype: int64

In [80]:
# very important function it is checking if there is any null values in the program or not
df.isnull().sum()

columns1    0
columns2    0
columns3    0
columns4    0
dtype: int64

In [90]:
# checking unique values column vise
df['columns2'].unique()

array([ 1,  5,  9, 13, 17])

In [8]:
mercedes_df = pd.read_csv("mercedesbenz.csv")
mercedes_df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [14]:
mercedes_df.describe()

In [15]:
mercedes_df.info()

In [23]:
mercedes_df['X0'].value_counts() # count how many times a particular value is getting repeated column wise

In [32]:
# mercedes_df[mercedes_df['y']>100]['y']

In [6]:
data=('col1,col2,col3\n''a,b,c\n''x,y,z\n''1,2,3')

In [7]:
data

'col1,col2,col3\na,b,c\nx,y,z\n1,2,3'

In [4]:
from io import StringIO

In [9]:
df1=pd.read_csv(StringIO(data)) # this is the use of StringIO function

In [10]:
# pd.read_csv(StringIO(data),usecols=['col1','col2']) #calling seperate columns

In [11]:
df1.to_csv("sample.csv")

In [12]:
df1=pd.read_csv(StringIO(data),dtype=object) #dtype is used to tell wether to make all columns string or integer
df1

col1 col2 col3
0    a    b    c
1    x    y    z
2    1    2    3

In [13]:
df1['col1'][2]

'1'

In [30]:
data2=('col1,col2,col3\n''15,16,17\n''28,29,30\n''31,32,33\n''34,35,36')

In [47]:
data3=pd.read_csv(StringIO(data2),dtype=float) #dtype is used to select the data type 
data4=pd.read_csv(StringIO(data2),dtype=int)
data5=pd.read_csv(StringIO(data2),dtype=object) # string
print(f"{data3}\n\n {data4} \n\n {data5}")

   col1  col2  col3
0  15.0  16.0  17.0
1  28.0  29.0  30.0
2  31.0  32.0  33.0
3  34.0  35.0  36.0

    col1  col2  col3
0    15    16    17
1    28    29    30
2    31    32    33
3    34    35    36 

   col1 col2 col3
0   15   16   17
1   28   29   30
2   31   32   33
3   34   35   36


In [50]:
data3['col3'][0], type(data3['col3'][0])

(17.0, numpy.float64)

In [52]:
data4['col3'][0], type(data4['col3'][0])

(17, numpy.int32)

In [55]:
data5['col3'][0], type(data5['col3'][0])

('17', str)

In [14]:
csv_data=('index,a,b,c\n''1,1,2,3\n''2,4,5,6\n')

In [24]:
data=pd.read_csv(StringIO(csv_data),dtype=None)
data1=pd.read_csv(StringIO(csv_data),index_col=0)
data2=pd.read_csv(StringIO(csv_data),index_col=False)
print(f"{data} \n\n{data1}\n\n {data2}")

   index  a  b  c
0      1  1  2  3
1      2  4  5  6 

       a  b  c
index         
1      1  2  3
2      4  5  6

    index  a  b  c
0      1  1  2  3
1      2  4  5  6


In [25]:
"""json"""

'json'

In [103]:
 names='{"Names": {"1":"James","2":"dhruv"}, "email": {"1":"james@gmail.com","2":"dhruvparikh291@gmail.com"}}'
names2='{"Courses":{"r1":"Spark"},"Duration":{"r1":"50 Days"}}'

In [104]:
pd.read_json(names)


Names                     email
1  James           james@gmail.com
2  dhruv  dhruvparikh291@gmail.com

In [112]:
wine_data=pd.read_csv("wine.csv")
wine_data.head()

Unnamed: 0  0      1     2     3     4    5     6     7     8     9    10  \
0           0  1  14.23  1.71  2.43  15.6  127  2.80  3.06  0.28  2.29  5.64   
1           1  1  13.20  1.78  2.14  11.2  100  2.65  2.76  0.26  1.28  4.38   
2           2  1  13.16  2.36  2.67  18.6  101  2.80  3.24  0.30  2.81  5.68   
3           3  1  14.37  1.95  2.50  16.8  113  3.85  3.49  0.24  2.18  7.80   
4           4  1  13.24  2.59  2.87  21.0  118  2.80  2.69  0.39  1.82  4.32   

     11    12    13  
0  1.04  3.92  1065  
1  1.05  3.40  1050  
2  1.03  3.17  1185  
3  0.86  3.45  1480  
4  1.04  2.93   735